### ISSUE TITLE
Another Thauminomicon Crash.

### ISSUE THREAD

**Issue by EzrahKarotan** [CanisArtorus/Gregorious-hexii-Artorus#12]
Another crash, same format, looked through the zs file this time though, and couldn't find any incorrect ingredients in the grid so far as I'm aware.. Full Bug report provided. This time it's the Arcane Crafting Terminal. 
https://pastebin.com/agvDPGLQ

**Comment by EzrahKarotan** [comment]
Found the source of the crash and fixed it locally, I'll drop the offending code here, and what it should be replaced with, as well as what file it was in so that it can be fixed on you guy's side.

// Arcane crafting terminal
Arcane.addShaped("thaumicenergistics.TEARCANETERM", <thaumicenergistics:part.base:5>, "ordo 10, perditio 10, aqua 10, ignis 10, terra 10, aer 10", 
	[[<ore:craftingToolScrewdriver>, <appliedenergistics2:item.ItemMultiPart:380>, <ore:craftingToolSoftHammer>], 
	[<ore:screwCertusQuartz>, <Thaumcraft:blockTable:15>, <ore:screwCertusQuartz>], 
	[<ore:plateNetherQuartz>, calcProc, <ore:plateNetherQuartz>]]);

Should be:

// Arcane crafting terminal
Arcane.addShaped("thaumicenergistics.TEARCANETERM", <thaumicenergistics:part.base:5>, "ordo 10, perditio 10, aqua 10, ignis 10, terra 10, aer 10", 
	[[<ore:craftingToolScrewdriver>, <appliedenergistics2:item.ItemMultiPart:380>, <ore:craftingToolSoftHammer>], 
	[<ore:screwCertusQuartz>, <Thaumcraft:blockTable:15>, <ore:screwCertusQuartz>], 
	[<ore:plateGemNetherQuartz>, calcProc, <ore:plateGemNetherQuartz>]]);

GT apparently has a different metatype for crystaline/gemstone plates than for normal ones (plateGem, as opposed to plate), I'll inform the you via discord about any other miss-typed recipes.

**Comment by CanisArtorus** [comment]
Found both of these. No crystalline plate errors found in the other two thaumic scripts.
