### ISSUE TITLE
mod

### ISSUE THREAD

**Issue by mightydanp** [CanisArtorus/Gregorious-hexii-Artorus#13]
what mod do i need to take out or change to get ride of your highway -_-

**Comment by CanisArtorus** [comment]
Config option, not a mod.
https://ftb.gamepedia.com/GregTech_6/Roads

in
$instance/config/GregTech/worldgenerationnew.cfg 
 you want to set
worldgenerator{ 
   streets{ 
      Enabled_false = false
(I have it as true)
